### ISSUE TITLE
Register provisioner documenation on Packer.io

### ISSUE THREAD

**Issue by nywilken** [mondoohq/packer-plugin-mondoo#19]
Hey there, your friendly Packer maintainer requesting that you add the provisioner documentation to the Packer.io site under https://packer.io/plugins/

We have a set of automated processes setup to help external plugins create and deploy their documentation. To start you would want to take a look at the [Registering Documentation on  Packer.io](https://github.com/hashicorp/packer-plugin-scaffolding#registering-documentation-on-packerio) documentation, which requires a `docs/` directory at the top-level directory of the plugin. 

Once you have the docs directory along with the provisioner documentation in place you can update the release configuration to generate the zip file needed for ingesting the documentation in Packer.io.

Quickly looking at the [configuration](https://github.com/mondoohq/packer-plugin-mondoo/blob/main/provisioner/provisioner.go#L35) for the provisioner I see that there are a number of configuration options. We have a tool as part of the `packer-sdc` command that you can use to automatically generate partial markdown files from the comments of each of the configurations. 

Here's a link to the [Ansible provisioner source](https://github.com/hashicorp/packer-plugin-ansible/blob/c6db679da38efe9d7423d214f762e3a9cf5a41a1/provisioner/ansible/provisioner.go#L2) where we include the `go generate` comment for generating markdown files from the configuration comments. Once that's  all in place and the partial files are generated you can reference the partials as includes in the markdown files under `docs/` which upon release can be merged together to create the final documentation files. 

I recommend you take a look at the [Ansible documentation directory](https://github.com/hashicorp/packer-plugin-ansible/blob/main/docs/provisioners/ansible.mdx?plain=1)  and files as an example to get a better gist of how all the pieces work together. 

As a last step, once all the docs are ready to go and released alongside the plugin binaries you can open a PR similar to this [ one ](https://github.com/hashicorp/packer/pull/11914) to complete the registration process. 

Please feel free to reach out if you have questions. Cheers!

**Comment by scottford-io** [comment]
@nywilken thanks for the heads up on this, and for the great docs on how to get it accomplished. We are going to work on getting the PR ready.

**Comment by nywilken** [comment]
> @nywilken thanks for the heads up on this, and for the great docs on how to get it accomplished. We are going to work on getting the PR ready.

Glad to help @scottford-io. Please feel free to reach out if there are any questions or inconsistencies with the docs/process. Cheers!

**Comment by scottford-io** [comment]
https://github.com/hashicorp/packer/pull/11951
