### ISSUE TITLE
Mondoo for vSphere builder ignores/not using communicator SSH password? 

### ISSUE THREAD

**Issue by mrdanielmartins** [mondoohq/packer-plugin-mondoo#40]
**Description**

Hello, Mondoo community! 

The Mondoo Packer provisioner seems to ignore the SSH communicator password - all other provisions, like Shell, work as expected.

I've tried to look at the other available options for the plugin, but I do not see anything relative to the SSH password (I do see options for SSH keys).

If I manually run a scan using `mondoo scan ssh` with `-p` option, it connects just fine.

I am wondering if any of you lot have come across this behaviour. Pardon me if I missed somewhere that only SSH keys are possible with the plugin.

Many thanks,

Daniel

**Additional context**
 - Workstation OS: `macOS Monterey 12.6`
 - Image OS: `Ubuntu Server Core 22.04 LTS`
 - vSphere: `6.7u3`
 - Packer: 
    - Version: `1.8.3`
    - Builder: `vSphere-ISO`
    - Plugins: 
        - `vsphere @ 1.0.8`
        - `mondoo @ 0.5.1`

**Screenshots**

<img width="1323" alt="image" src="https://user-images.githubusercontent.com/37153398/196930975-4bc0f288-b9c7-40bb-92d3-72378c4419a7.png">
<b>Packer build output</b>

<br>

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/37153398/196943596-fc275769-3c3b-455f-86a0-36256f3c18cb.png">
<b>Packer build output Mondoo set with debug.</b>

**Comment by chris-rock** [comment]
Thank you for reporting @mrdanielmartins We have a look and try to determine why this is happening.

**Comment by mrdanielmartins** [comment]
> Thank you for reporting @mrdanielmartins We have a look and try to determine why this is happening.

Thanks for the reply! I'll sit tight and await further updates. 🙏

**Comment by mrdanielmartins** [comment]
Update, I switched to using SSH keys. Works just fine with Packer (as you can see in the screenshot where it connects to SSH). However, Mondoo fails again - the plugin can't utilise the SSH key or SHH password or is it all empty? Additionally, it seems to error regarding the `ID` parameter. 

I'll try dropping to an earlier version in case something works. 

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/37153398/197155842-eb709647-8b22-4242-b5b7-b96a8a1d8990.png">

**Comment by preslavgerchev** [comment]
@mrdanielmartins thank you for reporting this, we've just rolled out a fix and a new release (0.5.2).
Could you test with it? It should now support both ssh passwords and ssh keys
